import {
  Code2,
  Palette,
  LineChart,
  Building2,
  GraduationCap,
  Microscope,
  Stethoscope,
  Briefcase,
  PenTool,
  Camera,
  Music,
  BookOpen,
  Globe,
  Heart,
  Leaf,
  Lightbulb,
  Rocket,
  Shield,
  Users,
  Wrench,
} from "lucide-react"

export const JOB_ICONS: Record<string, React.ElementType> = {
  "프론트엔드 개발자": Code2,
  "백엔드 개발자": Code2,
  "풀스택 개발자": Code2,
  "UX/UI 디자이너": Palette,
  "데이터 사이언티스트": LineChart,
  "비즈니스 분석가": Building2,
  "교사": GraduationCap,
  "연구원": Microscope,
  "의사": Stethoscope,
  "변호사": Briefcase,
  "그래픽 디자이너": PenTool,
  "사진작가": Camera,
  "음악가": Music,
  "작가": BookOpen,
  "번역가": Globe,
  "간호사": Heart,
  "환경 전문가": Leaf,
  "기획자": Lightbulb,
  "항공우주 엔지니어": Rocket,
  "보안 전문가": Shield,
  "HR 전문가": Users,
  "기계 엔지니어": Wrench,
}

// 기본 아이콘 (매핑되지 않은 직업에 사용)
export const DEFAULT_JOB_ICON = Briefcase 